version: "3"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    networks:
      - backend

  postgres:
    container_name: postgres
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - pg-data:/var/lib/postgresql/data
      
networks:
  backend:

volumes:
  pg-data: 